# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "AWS WEB APPLICATION FIREWALL"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://aws.amazon.com/blogs"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[Languages.vi]
title = "AWS WEB APPLICATION FIREWALL"
weight = 2
languageName = "Khmer"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nh√≥m FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

